
EXTRA_CFLAGS            += -Idrivers/multicore/common/
EXTRA_CFLAGS   		+= -Idrivers/multicore/icc/
EXTRA_CFLAGS   		+= -Idrivers/multicore/ipcm
obj-y			+= multi_test.o ICC_test.o IPC_test.o IFC_test.o

