obj-y             +=  uartDrv.o 
            
KBUILD_CPPFLAGS +=	-Iarch/arm/mach-balong/include/mach \
                        -Idrivers/mntn/include
                                            
                                            
                        	