ifeq ($(BOARD_TYPE), BOARD_ASIC_BIGPACK)
obj-y		:= BSP_PWC_SLEEPASM.o
endif
ifeq ($(BOARD_TYPE), BOARD_ASIC)
obj-y		:= BSP_PWC_SLEEPASM.o
endif
ifeq ($(BOARD_TYPE), BOARD_SFT)
obj-y		:= BSP_PWC_SLEEPASM.o
endif