obj-y             +=  omDrv.o 
obj-y             +=  usb_mntn.o
obj-y             +=  excDrv.o
obj-y             +=  icc_mntn.o
obj-y             +=  vxprintk.o
             
KBUILD_CPPFLAGS +=	-Iarch/arm/mach-balong/include/mach \
                        -Idrivers/mntn/include
                                            
                                            
                        	