# updateOnline

obj-y		+= updateOnline.o os_platform.o \
		   update_common.o
		   


KBUILD_CPPFLAGS +=	-Idrivers/mtd/nand/ptable \
			-Idrivers/mtd/nand/nandc  \
			-Iarch/arm/mach-balong/include/mach/common \
			-Idrivers/mmc/core 
			
