// MD5: 99da385decebc117b62f5e16c8d9f25b
#if !defined(__PRODUCT_CONFIG_H__)
#define __PRODUCT_CONFIG_H__

#ifndef BALONG_OBUILD_VERSION
#define BALONG_OBUILD_VERSION 10 
#endif // BALONG_OBUILD_VERSION

#ifndef PRODUCT_CFG_CHIP_SOLUTION_BALONG
#define PRODUCT_CFG_CHIP_SOLUTION_BALONG 
#endif // PRODUCT_CFG_CHIP_SOLUTION_BALONG

#ifndef PRODUCT_CFG_CHIP_SOLUTION_NAME
#define PRODUCT_CFG_CHIP_SOLUTION_NAME "Balong" 
#endif // PRODUCT_CFG_CHIP_SOLUTION_NAME

#ifndef PRODUCT_NAME
#define PRODUCT_NAME "HI6920CS_R215" 
#endif // PRODUCT_NAME

#ifndef BUILD_TYPE
#define BUILD_TYPE RELEASE 
#endif // BUILD_TYPE

#ifndef PRODUCT_VER
#define PRODUCT_VER V700R001C35B200 
#endif // PRODUCT_VER

#ifndef PRODUCT_CFG_VERSION_STR
#define PRODUCT_CFG_VERSION_STR "V700R001C35B200" 
#endif // PRODUCT_CFG_VERSION_STR

#ifndef PRODUCT_CFG_FULL_VERSION_STR
#define PRODUCT_CFG_FULL_VERSION_STR "Balong V700R001C35B200" 
#endif // PRODUCT_CFG_FULL_VERSION_STR

#ifndef PRODUCT_CFG_FILE_VERSION_STR
#define PRODUCT_CFG_FILE_VERSION_STR "2.2.0.0" 
#endif // PRODUCT_CFG_FILE_VERSION_STR

#ifndef PRODUCT_CFG_NV_VERSION_STR
#define PRODUCT_CFG_NV_VERSION_STR "1.2.1" 
#endif // PRODUCT_CFG_NV_VERSION_STR

#ifndef PRODUCT_CFG_BOOTLOADER_VERSION_STR
#define PRODUCT_CFG_BOOTLOADER_VERSION_STR "1.0.0" 
#endif // PRODUCT_CFG_BOOTLOADER_VERSION_STR

#ifndef PRODUCT_CFG_VERSION_V
#define PRODUCT_CFG_VERSION_V 700 
#endif // PRODUCT_CFG_VERSION_V

#ifndef PRODUCT_CFG_VERSION_R
#define PRODUCT_CFG_VERSION_R 001 
#endif // PRODUCT_CFG_VERSION_R

#ifndef PRODUCT_CFG_VERSION_C
#define PRODUCT_CFG_VERSION_C 35 
#endif // PRODUCT_CFG_VERSION_C

#ifndef PRODUCT_CFG_VERSION_B
#define PRODUCT_CFG_VERSION_B 200 
#endif // PRODUCT_CFG_VERSION_B

#ifndef PRODUCT_CFG_VERSION_RELEASE
#define PRODUCT_CFG_VERSION_RELEASE 
#endif // PRODUCT_CFG_VERSION_RELEASE

#ifndef PRODUCT_CFG_ENABLE_SHELL_SYM   			
#define PRODUCT_CFG_ENABLE_SHELL_SYM   			 
#endif // PRODUCT_CFG_ENABLE_SHELL_SYM   			

#ifndef NV_INCLUDE_PRIORITY			
#define NV_INCLUDE_PRIORITY			 1 
#endif // NV_INCLUDE_PRIORITY			

#ifndef FEATURE_OBJ_CMP
#endif // FEATURE_OBJ_CMP

#ifndef FEATURE_OBJ_DUMP
#endif // FEATURE_OBJ_DUMP

#ifndef FIRMWARE_DIR_NAME	    			
#define FIRMWARE_DIR_NAME	    			 "makeFirmware_GL04P" 
#endif // FIRMWARE_DIR_NAME	    			

#ifndef PRODUCT_CFG_ISO_NAME
#define PRODUCT_CFG_ISO_NAME "MOBILE_CONNECT" 
#endif // PRODUCT_CFG_ISO_NAME

#ifndef PRODUCT_CFG_ISO_VER
#define PRODUCT_CFG_ISO_VER "UTPS21.005.18.00.03" 
#endif // PRODUCT_CFG_ISO_VER

#ifndef PRODUCT_CFG_DLOAD_ID
#define PRODUCT_CFG_DLOAD_ID "B710D0" 
#endif // PRODUCT_CFG_DLOAD_ID

#ifndef PRODUCT_CFG_DLOAD_NAME
#define PRODUCT_CFG_DLOAD_NAME "R215" 
#endif // PRODUCT_CFG_DLOAD_NAME

#ifndef PRODUCT_CFG_DLOAD_TOOL_VER
#define PRODUCT_CFG_DLOAD_TOOL_VER "B312" 
#endif // PRODUCT_CFG_DLOAD_TOOL_VER

#ifndef PRODUCT_CFG_DLOAD_SOFTWARE_VER
#define PRODUCT_CFG_DLOAD_SOFTWARE_VER "21.221.21.00.11" 
#endif // PRODUCT_CFG_DLOAD_SOFTWARE_VER

#ifndef PRODUCT_CFG_DLOAD_SECOND_VER
#define PRODUCT_CFG_DLOAD_SECOND_VER "UTPS12.001.22.00.03" 
#endif // PRODUCT_CFG_DLOAD_SECOND_VER

#ifndef PRODUCT_CFG_DLOAD_CFG
#define PRODUCT_CFG_DLOAD_CFG "Bin2App.E5.cfg" 
#endif // PRODUCT_CFG_DLOAD_CFG

#ifndef PRODUCT_CFG_DLOAD_CFG_GZ
#define PRODUCT_CFG_DLOAD_CFG_GZ "Bin2App.E5.gz.cfg" 
#endif // PRODUCT_CFG_DLOAD_CFG_GZ

#ifndef PRODUCT_CFG_DLOAD_CFG_WEBUI
#define PRODUCT_CFG_DLOAD_CFG_WEBUI "Bin2App.E5.webui.cfg" 
#endif // PRODUCT_CFG_DLOAD_CFG_WEBUI

#ifndef PRODUCT_CFG_DLOAD_CFG_GZ_WEBUI
#define PRODUCT_CFG_DLOAD_CFG_GZ_WEBUI "Bin2App.E5.webui.gz.cfg" 
#endif // PRODUCT_CFG_DLOAD_CFG_GZ_WEBUI

#ifndef PRODUCT_CFG_DLOAD_CFG_3IN1
#define PRODUCT_CFG_DLOAD_CFG_3IN1 "Bin2App.E5.3in1.cfg" 
#endif // PRODUCT_CFG_DLOAD_CFG_3IN1

#ifndef PRODUCT_CFG_DLOAD_CFG_GZ_3IN1
#define PRODUCT_CFG_DLOAD_CFG_GZ_3IN1 "Bin2App.E5.3in1.gz.cfg" 
#endif // PRODUCT_CFG_DLOAD_CFG_GZ_3IN1

#ifndef PRODUCT_CFG_DLOAD_PACK_BAT
#define PRODUCT_CFG_DLOAD_PACK_BAT "Make.bat" 
#endif // PRODUCT_CFG_DLOAD_PACK_BAT

#ifndef PRODUCT_CFG_HARDWARE_PCB_NAME
#define PRODUCT_CFG_HARDWARE_PCB_NAME "03020QXR" 
#endif // PRODUCT_CFG_HARDWARE_PCB_NAME

#ifndef PRODUCT_CFG_HARDWARE_NAME_PRIVATE
#define PRODUCT_CFG_HARDWARE_NAME_PRIVATE "MT1B390A" 
#endif // PRODUCT_CFG_HARDWARE_NAME_PRIVATE

#ifndef PRODUCT_CFG_HARDWARE_NAME     	
#define PRODUCT_CFG_HARDWARE_NAME     	 "Hi6920" 
#endif // PRODUCT_CFG_HARDWARE_NAME     	

#ifndef PKG_APP_IMG			
#define PKG_APP_IMG			 
#endif // PKG_APP_IMG			

#ifndef APP_IMG_DIR
#define APP_IMG_DIR "r215" 
#endif // APP_IMG_DIR

#ifndef PKG_WEBUI_IMG		
#endif // PKG_WEBUI_IMG		

#ifndef DLOAD_PACK_FILELIST
#define DLOAD_PACK_FILELIST MakeBalongV7R1_LV_E5 
#endif // DLOAD_PACK_FILELIST

#ifndef PKG_MOBILE_CONNECT_ISO	
#endif // PKG_MOBILE_CONNECT_ISO	

#ifndef USE_USBLOADER_MERGE				
#define USE_USBLOADER_MERGE				 
#endif // USE_USBLOADER_MERGE				

#ifndef USBLOADER_MERGE_BIN				
#define USBLOADER_MERGE_BIN				 ramInit_128M_CS.bin 
#endif // USBLOADER_MERGE_BIN				

#ifndef CHIP_BB_6920CS
#define CHIP_BB_6920CS 
#endif // CHIP_BB_6920CS

#ifndef CHIP_BB
#define CHIP_BB 6920CS 
#endif // CHIP_BB

#ifndef CHIP_PMU_6451ES0
#define CHIP_PMU_6451ES0 
#endif // CHIP_PMU_6451ES0

#ifndef CHIP_RFIC_6360V200
#define CHIP_RFIC_6360V200 
#endif // CHIP_RFIC_6360V200

#ifndef BOARD_ASIC
#define BOARD_ASIC 
#endif // BOARD_ASIC

#ifndef BOARD
#define BOARD ASIC 
#endif // BOARD

#ifndef FEATURE_MULTIMODE_GUL
#define FEATURE_MULTIMODE_GUL 
#endif // FEATURE_MULTIMODE_GUL

#ifndef PRODUCT_CFG_MULTIMODE_GUL
#define PRODUCT_CFG_MULTIMODE_GUL 
#endif // PRODUCT_CFG_MULTIMODE_GUL

#ifndef LALG_PATH
#define LALG_PATH COMM_CODE/Balong_MultiMode_Inc/chipset/hi6920cs 
#endif // LALG_PATH

#ifndef CHIPSET_PATH
#define CHIPSET_PATH COMM_CODE/Balong_MultiMode_Inc/chipset/hi6920cs 
#endif // CHIPSET_PATH

#ifndef OS_PATH
#define OS_PATH COMM_CODE/product/hi6920cs_R215/os 
#endif // OS_PATH

#ifndef OS_LINUX_PRODUCT_NAME
#define OS_LINUX_PRODUCT_NAME hisi_balong_hi6920cs_e5776s_defconfig 
#endif // OS_LINUX_PRODUCT_NAME

#ifndef OS_ANDROID_PRODUCT_NAME
#define OS_ANDROID_PRODUCT_NAME hi6920cs_asic 
#endif // OS_ANDROID_PRODUCT_NAME

#ifndef GU_NV_PATH
#define GU_NV_PATH COMM_CODE/Balong_GU_Inc/NVIM/NvData/V7R1/Product/bin 
#endif // GU_NV_PATH

#ifndef GU_NV_XML_PATH
#define GU_NV_XML_PATH COMM_CODE/Balong_GU_Inc/NVIM/NvData/V7R1/Product/cs_e5_gtl 
#endif // GU_NV_XML_PATH

#ifndef GU_NV_XML_FLAG
#define GU_NV_XML_FLAG 
#endif // GU_NV_XML_FLAG

#ifndef LNV_PRO_NAME
#define LNV_PRO_NAME hi6920cs_e5776s 
#endif // LNV_PRO_NAME

#ifndef XTENSA_CORE
#define XTENSA_CORE Balong_V7R1_BBE16_prod 
#endif // XTENSA_CORE

#ifndef XTENSA_SYSTEM
#define XTENSA_SYSTEM $(TENSILICA_BUILDS)/Balong_V7R1_BBE16_prod/config 
#endif // XTENSA_SYSTEM

#ifndef LD_MAP_PATH
#define LD_MAP_PATH PHY_CODE/Tensilica_LSP/hi6920cs-lphy-asic-bbe16-lsp 
#endif // LD_MAP_PATH

#ifndef GU_INC_PATH
#define GU_INC_PATH COMM_CODE_GU/Balong_GU_Inc/GTL_CS 
#endif // GU_INC_PATH

#ifndef GU_PRODUCT_VERSION
#define GU_PRODUCT_VERSION VERSION_V7R1 
#endif // GU_PRODUCT_VERSION

#ifndef GU_RAT_MODE
#define GU_RAT_MODE RAT_GTL 
#endif // GU_RAT_MODE

#ifndef GU_PLATFORM
#define GU_PLATFORM GTL_CS 
#endif // GU_PLATFORM

#ifndef GU_PLATFORM_NEW
#define GU_PLATFORM_NEW HI6920CS_ASIC 
#endif // GU_PLATFORM_NEW

#ifndef GU_FEATURE_CONFIG_PATH
#define GU_FEATURE_CONFIG_PATH COMM_CODE/Config/HI6920CS_R215 
#endif // GU_FEATURE_CONFIG_PATH

#ifndef HIFI_LINK_DIR_NAME			
#define HIFI_LINK_DIR_NAME			 hifi_ld_V7R1_CS_UDP_STICK 
#endif // HIFI_LINK_DIR_NAME			

#ifndef ZSP_LINK_FILE_NAME			
#define ZSP_LINK_FILE_NAME			 ZSP_V7R1.ld 
#endif // ZSP_LINK_FILE_NAME			

#ifndef ZSP_DSP_CHIP_BB_TYPE		
#define ZSP_DSP_CHIP_BB_TYPE		 2 
#endif // ZSP_DSP_CHIP_BB_TYPE		

#ifndef ZSP_DSP_PRODUCT_FORM		
#define ZSP_DSP_PRODUCT_FORM		 1 
#endif // ZSP_DSP_PRODUCT_FORM		

#ifndef FEATURE_E5776S_860
#define FEATURE_E5776S_860 
#endif // FEATURE_E5776S_860

#ifndef FEATURE_CHARGE_ON
#define FEATURE_CHARGE_ON 
#endif // FEATURE_CHARGE_ON

#ifndef FEATURE_HUAWEI_MBB_CHG
#define FEATURE_HUAWEI_MBB_CHG 
#endif // FEATURE_HUAWEI_MBB_CHG

#ifndef FEATURE_HUAWEI_MBB_CHG_VXWORKS
#define FEATURE_HUAWEI_MBB_CHG_VXWORKS 
#endif // FEATURE_HUAWEI_MBB_CHG_VXWORKS

#ifndef FEATURE_HUAWEI_MBB_CHG_LCD
#define FEATURE_HUAWEI_MBB_CHG_LCD 
#endif // FEATURE_HUAWEI_MBB_CHG_LCD

#ifndef FEATURE_HUAWEI_MBB_CHG_LED
#endif // FEATURE_HUAWEI_MBB_CHG_LED

#ifndef FEATURE_HUAWEI_MBB_CHG_COMPENSATE
#define FEATURE_HUAWEI_MBB_CHG_COMPENSATE 
#endif // FEATURE_HUAWEI_MBB_CHG_COMPENSATE

#ifndef FEATURE_HUAWEI_MBB_CHG_BQ24161
#define FEATURE_HUAWEI_MBB_CHG_BQ24161 
#endif // FEATURE_HUAWEI_MBB_CHG_BQ24161

#ifndef FEATURE_HUAWEI_MBB_CHG_MAX8903
#endif // FEATURE_HUAWEI_MBB_CHG_MAX8903

#ifndef FEATURE_HUAWEI_MBB_CHG_WARM_CHARGE
#define FEATURE_HUAWEI_MBB_CHG_WARM_CHARGE 
#endif // FEATURE_HUAWEI_MBB_CHG_WARM_CHARGE

#ifndef FEATURE_SAR_REDUCTION
#define FEATURE_SAR_REDUCTION 
#endif // FEATURE_SAR_REDUCTION

#ifndef FEATURE_KEYBOARD_ON
#define FEATURE_KEYBOARD_ON 
#endif // FEATURE_KEYBOARD_ON

#ifndef FEATURE_POWER_ON_OFF_ON
#define FEATURE_POWER_ON_OFF_ON 
#endif // FEATURE_POWER_ON_OFF_ON

#ifndef FEATURE_BOARD_STUB_BJ_E5776S
#define FEATURE_BOARD_STUB_BJ_E5776S 
#endif // FEATURE_BOARD_STUB_BJ_E5776S

#ifndef FEATURE_E5_ON
#define FEATURE_E5_ON 
#endif // FEATURE_E5_ON

#ifndef FEATURE_LCD_BOTTOM
#endif // FEATURE_LCD_BOTTOM

#ifndef FEATURE_SIM_NOTIFY
#define FEATURE_SIM_NOTIFY 
#endif // FEATURE_SIM_NOTIFY

#ifndef FEATURE_SHORT_ON_OFF
#define FEATURE_SHORT_ON_OFF 
#endif // FEATURE_SHORT_ON_OFF

#ifndef FEATURE_LCD_TURN_RIGHT
#define FEATURE_LCD_TURN_RIGHT 
#endif // FEATURE_LCD_TURN_RIGHT

#ifndef FEATURE_MENU_DISPLAY
#define FEATURE_MENU_DISPLAY 
#endif // FEATURE_MENU_DISPLAY

#ifndef FEATURE_LCD_ON
#define FEATURE_LCD_ON 
#endif // FEATURE_LCD_ON

#ifndef FEATURE_KEY_2S
#define FEATURE_KEY_2S 
#endif // FEATURE_KEY_2S

#ifndef FEATURE_BSP_FASTBOOT_OPTI
#define FEATURE_BSP_FASTBOOT_OPTI 
#endif // FEATURE_BSP_FASTBOOT_OPTI

#ifndef BOOT_OPTI_ENABLE_CACHE
#define BOOT_OPTI_ENABLE_CACHE 
#endif // BOOT_OPTI_ENABLE_CACHE

#ifndef BOOT_OPTI_DSP_READ_FILE
#define BOOT_OPTI_DSP_READ_FILE 
#endif // BOOT_OPTI_DSP_READ_FILE

#ifndef BOOT_OPTI_NANDC_CPY
#define BOOT_OPTI_NANDC_CPY 
#endif // BOOT_OPTI_NANDC_CPY

#ifndef BOOT_OPTI_YAFFS_TAGS
#define BOOT_OPTI_YAFFS_TAGS 
#endif // BOOT_OPTI_YAFFS_TAGS

#ifndef BOOT_OPTI_TASKDELAY
#define BOOT_OPTI_TASKDELAY 
#endif // BOOT_OPTI_TASKDELAY

#ifndef BOOT_OPTI_BUILDIN
#define BOOT_OPTI_BUILDIN 
#endif // BOOT_OPTI_BUILDIN

#ifndef BOOT_OPTI_HKADC_WGRF
#define BOOT_OPTI_HKADC_WGRF 
#endif // BOOT_OPTI_HKADC_WGRF

#ifndef FEATURE_AXI_MONITOR
#define FEATURE_AXI_MONITOR 
#endif // FEATURE_AXI_MONITOR

#ifndef BSP_ASIC_DIR_NAME
#define BSP_ASIC_DIR_NAME v7r1 
#endif // BSP_ASIC_DIR_NAME

#ifndef PRODUCT_CFG_ENABLE_BUILD_VARS
#define PRODUCT_CFG_ENABLE_BUILD_VARS 
#endif // PRODUCT_CFG_ENABLE_BUILD_VARS

#ifndef PRODUCT_CFG_PRODUCT_TYPE_HI6920ES_E5776S
#define PRODUCT_CFG_PRODUCT_TYPE_HI6920ES_E5776S 
#endif // PRODUCT_CFG_PRODUCT_TYPE_HI6920ES_E5776S

#ifndef FEATURE_WIFI_ON
#define FEATURE_WIFI_ON 
#endif // FEATURE_WIFI_ON

#ifndef KERNEL_MANAGE_SUSPEND
#define KERNEL_MANAGE_SUSPEND 
#endif // KERNEL_MANAGE_SUSPEND

#ifndef FEATURE_WIFI_CHIP_VER
#define FEATURE_WIFI_CHIP_VER BCM43241 
#endif // FEATURE_WIFI_CHIP_VER

#ifndef FEATURE_WIFI_OFFLOAD
#define FEATURE_WIFI_OFFLOAD 
#endif // FEATURE_WIFI_OFFLOAD

#ifndef HUAWEI_FEATURE_43241_WIFI_PMU
#define HUAWEI_FEATURE_43241_WIFI_PMU 
#endif // HUAWEI_FEATURE_43241_WIFI_PMU

#ifndef FEATURE_SD_ENABLE
#define FEATURE_SD_ENABLE 
#endif // FEATURE_SD_ENABLE

#ifndef FEATURE_NCM_ON
#define FEATURE_NCM_ON 
#endif // FEATURE_NCM_ON

#ifndef FEATURE_ECM_OFF
#define FEATURE_ECM_OFF 
#endif // FEATURE_ECM_OFF

#ifndef FEATURE_BSP_SOFTTIMER			
#define FEATURE_BSP_SOFTTIMER			 
#endif // FEATURE_BSP_SOFTTIMER			

#ifndef FEATURE_BSP_I2C					
#define FEATURE_BSP_I2C					 
#endif // FEATURE_BSP_I2C					

#ifndef FEATURE_BSP_EFUSE				
#define FEATURE_BSP_EFUSE				 
#endif // FEATURE_BSP_EFUSE				

#ifndef FEATURE_BSP_PWRCTRL				
#define FEATURE_BSP_PWRCTRL				 
#endif // FEATURE_BSP_PWRCTRL				

#ifndef FEATURE_BSP_HKADC				
#define FEATURE_BSP_HKADC				 
#endif // FEATURE_BSP_HKADC				

#ifndef FEATURE_BSP_SSDMA				
#endif // FEATURE_BSP_SSDMA				

#ifndef FEATURE_BSP_POWER_DRX			
#endif // FEATURE_BSP_POWER_DRX			

#ifndef FEATURE_BSP_LCD					
#define FEATURE_BSP_LCD					 
#endif // FEATURE_BSP_LCD					

#ifndef FEATURE_BSP_CHG					
#define FEATURE_BSP_CHG					 
#endif // FEATURE_BSP_CHG					

#ifndef FEATURE_BSP_SHELL				
#define FEATURE_BSP_SHELL				 
#endif // FEATURE_BSP_SHELL				

#ifndef FEATURE_BSP_LANSWITCH			
#endif // FEATURE_BSP_LANSWITCH			

#ifndef FEATURE_BSP_WM8990				
#define FEATURE_BSP_WM8990				 
#endif // FEATURE_BSP_WM8990				

#ifndef FEATURE_BSP_HIFI				
#define FEATURE_BSP_HIFI				 
#endif // FEATURE_BSP_HIFI				

#ifndef FEATURE_BSP_TDS
#define FEATURE_BSP_TDS 
#endif // FEATURE_BSP_TDS

#ifndef ENABLE_SHELL_SYM				
#define ENABLE_SHELL_SYM				 
#endif // ENABLE_SHELL_SYM				

#ifndef MCORE_COMPONENTS			
#define MCORE_COMPONENTS			 lbsp_mcore.o gumsp_mcore.o gups_AS_mcore.o gups_NAS_mcore.o lps_AS_mcore.o lps_NAS_mcore.o  lmsp_mcore.o  os_mcore.o 
#endif // MCORE_COMPONENTS			

#ifndef BOOTROM_COMPONENTS			
#define BOOTROM_COMPONENTS			 lbsp_bootrom.o lmsp_bootrom.o os_bootrom.o 
#endif // BOOTROM_COMPONENTS			

#ifndef PRODUCT_CFG_BUILD_SEPARATE					
#endif // PRODUCT_CFG_BUILD_SEPARATE					

#ifndef PRODUCT_CFG_ENABLE_TEST_CODE				
#endif // PRODUCT_CFG_ENABLE_TEST_CODE				

#ifndef PTABLE_TRANSITION	
#endif // PTABLE_TRANSITION	

#ifndef PRODUCT_CFG_SUPPORT_MOUNT_MTD	
#define PRODUCT_CFG_SUPPORT_MOUNT_MTD	 
#endif // PRODUCT_CFG_SUPPORT_MOUNT_MTD	

#ifndef PRODUCT_CFG_PTABLE_ISOVER_IN_YAFFS	
#define PRODUCT_CFG_PTABLE_ISOVER_IN_YAFFS	 
#endif // PRODUCT_CFG_PTABLE_ISOVER_IN_YAFFS	

#ifndef FEATURE_HUAWEI_E5_FLASH_PTABLE
#define FEATURE_HUAWEI_E5_FLASH_PTABLE 
#endif // FEATURE_HUAWEI_E5_FLASH_PTABLE

#ifndef PRODUCT_CFG_ISO_INCLUDE
#define PRODUCT_CFG_ISO_INCLUDE YES;  YES;  YES;  YES 
#endif // PRODUCT_CFG_ISO_INCLUDE

#ifndef PRODUCT_CFG_PTABLE_STUB_DLOAD_ID
#define PRODUCT_CFG_PTABLE_STUB_DLOAD_ID "H69DUSAVA" 
#endif // PRODUCT_CFG_PTABLE_STUB_DLOAD_ID

#ifndef PRODUCT_CFG_PTABLE_STUB_DLOAD_NAME
#define PRODUCT_CFG_PTABLE_STUB_DLOAD_NAME "H69DUSAVA" 
#endif // PRODUCT_CFG_PTABLE_STUB_DLOAD_NAME

#ifndef PRODUCT_CFG_PTABLE_STUB_DLOAD_VER
#define PRODUCT_CFG_PTABLE_STUB_DLOAD_VER "71.080.10.00.00" 
#endif // PRODUCT_CFG_PTABLE_STUB_DLOAD_VER

#ifndef BSP_BL_CRC_ENABLE				
#endif // BSP_BL_CRC_ENABLE				

#ifndef BSP_BL_TEXT_ENTRY_ADR		
#define BSP_BL_TEXT_ENTRY_ADR		 0x2ffc0000 
#endif // BSP_BL_TEXT_ENTRY_ADR		

#ifndef NANDF_ADDR_CYCLES 		
#define NANDF_ADDR_CYCLES 		 5 
#endif // NANDF_ADDR_CYCLES 		

#ifndef NANDF_PAGE_SIZE 		
#define NANDF_PAGE_SIZE 		 2048 
#endif // NANDF_PAGE_SIZE 		

#ifndef NANDF_PAGES_PER_BLOCK 	
#define NANDF_PAGES_PER_BLOCK 	 64 
#endif // NANDF_PAGES_PER_BLOCK 	

#ifndef NANDF_FLASH_CAPACITY	
#define NANDF_FLASH_CAPACITY	 0x10000000 
#endif // NANDF_FLASH_CAPACITY	

#ifndef CAS_LATENCY			
#define CAS_LATENCY			 3 
#endif // CAS_LATENCY			

#ifndef BSP_BL_VER_V		
#define BSP_BL_VER_V		 007 
#endif // BSP_BL_VER_V		

#ifndef BSP_BL_VER_R		
#define BSP_BL_VER_R		 001 
#endif // BSP_BL_VER_R		

#ifndef BSP_BL_VER_C		
#define BSP_BL_VER_C		 035 
#endif // BSP_BL_VER_C		

#ifndef BSP_BL_VER_B		
#define BSP_BL_VER_B		 200 
#endif // BSP_BL_VER_B		

#ifndef PRODUCT_CFG_PTABLE_VER_NAME
#define PRODUCT_CFG_PTABLE_VER_NAME "H6920CS_R215" 
#endif // PRODUCT_CFG_PTABLE_VER_NAME

#ifndef PRODUCT_CFG_PTABLE_BOOTROM_VER
#define PRODUCT_CFG_PTABLE_BOOTROM_VER "BOOTROM_V01.02" 
#endif // PRODUCT_CFG_PTABLE_BOOTROM_VER

#ifndef PRODUCT_CFG_FLASH_TOTAL_SIZE     	
#define PRODUCT_CFG_FLASH_TOTAL_SIZE     	 0x10000000 
#endif // PRODUCT_CFG_FLASH_TOTAL_SIZE     	

#ifndef PRODUCT_CFG_FLASH_ANDROID_FASTBOOT_LOADSIZE_LEN
#define PRODUCT_CFG_FLASH_ANDROID_FASTBOOT_LOADSIZE_LEN 0x20000 
#endif // PRODUCT_CFG_FLASH_ANDROID_FASTBOOT_LOADSIZE_LEN

#ifndef PRODUCT_CFG_FLASH_BOOTLOADER_LEN
#define PRODUCT_CFG_FLASH_BOOTLOADER_LEN 0x20000 
#endif // PRODUCT_CFG_FLASH_BOOTLOADER_LEN

#ifndef PRODUCT_CFG_FLASH_NV_LTE_LEN
#define PRODUCT_CFG_FLASH_NV_LTE_LEN 0x180000 
#endif // PRODUCT_CFG_FLASH_NV_LTE_LEN

#ifndef PRODUCT_CFG_FLASH_NV_GU_LEN
#define PRODUCT_CFG_FLASH_NV_GU_LEN 0x100000 
#endif // PRODUCT_CFG_FLASH_NV_GU_LEN

#ifndef PRODUCT_CFG_FLASH_BOOTROM_A_LEN
#define PRODUCT_CFG_FLASH_BOOTROM_A_LEN 0x200000 
#endif // PRODUCT_CFG_FLASH_BOOTROM_A_LEN

#ifndef PRODUCT_CFG_FLASH_BOOTROM_B_LEN
#define PRODUCT_CFG_FLASH_BOOTROM_B_LEN 0x200000 
#endif // PRODUCT_CFG_FLASH_BOOTROM_B_LEN

#ifndef PRODUCT_CFG_FLASH_VXWORKS_MCORE_LEN
#define PRODUCT_CFG_FLASH_VXWORKS_MCORE_LEN 0x2000000 
#endif // PRODUCT_CFG_FLASH_VXWORKS_MCORE_LEN

#ifndef PRODUCT_CFG_FLASH_LOGO_LEN
#define PRODUCT_CFG_FLASH_LOGO_LEN 0x100000 
#endif // PRODUCT_CFG_FLASH_LOGO_LEN

#ifndef PRODUCT_CFG_FLASH_YAFFS_MCORE_LEN	
#define PRODUCT_CFG_FLASH_YAFFS_MCORE_LEN	 0xC00000 
#endif // PRODUCT_CFG_FLASH_YAFFS_MCORE_LEN	

#ifndef PRODUCT_CFG_FLASH_ANDROID_FASTBOOT_LEN
#define PRODUCT_CFG_FLASH_ANDROID_FASTBOOT_LEN 0x60000 
#endif // PRODUCT_CFG_FLASH_ANDROID_FASTBOOT_LEN

#ifndef PRODUCT_CFG_FLASH_ANDROID_BOOTIMAGE_LEN
#define PRODUCT_CFG_FLASH_ANDROID_BOOTIMAGE_LEN 0x3A0000 
#endif // PRODUCT_CFG_FLASH_ANDROID_BOOTIMAGE_LEN

#ifndef PRODUCT_CFG_FLASH_YAFFS_ACORE_LEN
#define PRODUCT_CFG_FLASH_YAFFS_ACORE_LEN 0x1C00000 
#endif // PRODUCT_CFG_FLASH_YAFFS_ACORE_LEN

#ifndef PRODUCT_CFG_FLASH_YAFFS_APP_LEN        	
#define PRODUCT_CFG_FLASH_YAFFS_APP_LEN        	 0x700000 
#endif // PRODUCT_CFG_FLASH_YAFFS_APP_LEN        	

#ifndef PRODUCT_CFG_FLASH_YAFFS_OEM_LEN
#define PRODUCT_CFG_FLASH_YAFFS_OEM_LEN 0x200000 
#endif // PRODUCT_CFG_FLASH_YAFFS_OEM_LEN

#ifndef PRODUCT_CFG_FLASH_YAFFS_USERDATA_LEN
#define PRODUCT_CFG_FLASH_YAFFS_USERDATA_LEN 0x800000 
#endif // PRODUCT_CFG_FLASH_YAFFS_USERDATA_LEN

#ifndef PRODUCT_CFG_FLASH_YAFFS_WEBUI_LEN		
#define PRODUCT_CFG_FLASH_YAFFS_WEBUI_LEN		 0x1400000 
#endif // PRODUCT_CFG_FLASH_YAFFS_WEBUI_LEN		

#ifndef PRODUCT_CFG_FLASH_YAFFS_ONLINE_LEN 		
#define PRODUCT_CFG_FLASH_YAFFS_ONLINE_LEN 		 0x6460000 
#endif // PRODUCT_CFG_FLASH_YAFFS_ONLINE_LEN 		

#ifndef PRODUCT_CFG_FLASH_ISO_LEN
#define PRODUCT_CFG_FLASH_ISO_LEN 0x2200000 
#endif // PRODUCT_CFG_FLASH_ISO_LEN

#ifndef FEATURE_DDRTYPE_LPDDR1
#define FEATURE_DDRTYPE_LPDDR1 
#endif // FEATURE_DDRTYPE_LPDDR1

#ifndef FEATURE_DDRSIZE_128M
#define FEATURE_DDRSIZE_128M 
#endif // FEATURE_DDRSIZE_128M

#ifndef FEATURE_PHYDDRSIZE_128M
#define FEATURE_PHYDDRSIZE_128M 
#endif // FEATURE_PHYDDRSIZE_128M

#ifndef PRODUCT_CFG_MCORE_RAM_LOW_ADDR
#define PRODUCT_CFG_MCORE_RAM_LOW_ADDR 0x30004000 
#endif // PRODUCT_CFG_MCORE_RAM_LOW_ADDR

#ifndef PRODUCT_CFG_MCORE_RAM_HIGH_ADDR
#define PRODUCT_CFG_MCORE_RAM_HIGH_ADDR 0x33D00000 
#endif // PRODUCT_CFG_MCORE_RAM_HIGH_ADDR

#ifndef PRODUCT_CFG_BOOTROM_RAM_LOW_ADDR
#define PRODUCT_CFG_BOOTROM_RAM_LOW_ADDR 0x30004000 
#endif // PRODUCT_CFG_BOOTROM_RAM_LOW_ADDR

#ifndef PRODUCT_CFG_BOOTROM_RAM_HIGH_ADDR
#define PRODUCT_CFG_BOOTROM_RAM_HIGH_ADDR 0x33D00000 
#endif // PRODUCT_CFG_BOOTROM_RAM_HIGH_ADDR

#ifndef PRODUCT_CFG_FASTBOOT_ENTRY
#define PRODUCT_CFG_FASTBOOT_ENTRY 0x36AE0000 
#endif // PRODUCT_CFG_FASTBOOT_ENTRY

#ifndef PRODUCT_CFG_KERNEL_ENTRY
#define PRODUCT_CFG_KERNEL_ENTRY 0x36A00000 
#endif // PRODUCT_CFG_KERNEL_ENTRY

#ifndef GLOBAL_MEM_BASE_ADDR
#define GLOBAL_MEM_BASE_ADDR 0x30000000 
#endif // GLOBAL_MEM_BASE_ADDR

#ifndef GLOBAL_MEM_ACORE_ACP_ADDR
#define GLOBAL_MEM_ACORE_ACP_ADDR GLOBAL_MEM_BASE_ADDR 
#endif // GLOBAL_MEM_ACORE_ACP_ADDR

#ifndef GLOBAL_MEM_ACORE_ACP_SIZE
#define GLOBAL_MEM_ACORE_ACP_SIZE 0x000000 
#endif // GLOBAL_MEM_ACORE_ACP_SIZE

#ifndef GLOBAL_MEM_MCORE_BASE_ADDR
#define GLOBAL_MEM_MCORE_BASE_ADDR ((GLOBAL_MEM_ACORE_ACP_ADDR) + (GLOBAL_MEM_ACORE_ACP_SIZE)) 
#endif // GLOBAL_MEM_MCORE_BASE_ADDR

#ifndef GLOBAL_MEM_MCORE_BASE_SIZE
#define GLOBAL_MEM_MCORE_BASE_SIZE 0x3CFA000 
#endif // GLOBAL_MEM_MCORE_BASE_SIZE

#ifndef GLOBAL_MEM_MCORE_PM_RESERVED_ADDR
#define GLOBAL_MEM_MCORE_PM_RESERVED_ADDR ((GLOBAL_MEM_MCORE_BASE_ADDR) + (GLOBAL_MEM_MCORE_BASE_SIZE)) 
#endif // GLOBAL_MEM_MCORE_PM_RESERVED_ADDR

#ifndef GLOBAL_MEM_MCORE_PM_RESERVED_SIZE
#define GLOBAL_MEM_MCORE_PM_RESERVED_SIZE 0x6000 
#endif // GLOBAL_MEM_MCORE_PM_RESERVED_SIZE

#ifndef GLOBAL_MEM_MCORE_USER_RESERVED_ADDR
#define GLOBAL_MEM_MCORE_USER_RESERVED_ADDR ((GLOBAL_MEM_MCORE_PM_RESERVED_ADDR) + (GLOBAL_MEM_MCORE_PM_RESERVED_SIZE)) 
#endif // GLOBAL_MEM_MCORE_USER_RESERVED_ADDR

#ifndef GLOBAL_MEM_MCORE_USER_RESERVED_SIZE
#define GLOBAL_MEM_MCORE_USER_RESERVED_SIZE 0x100000 
#endif // GLOBAL_MEM_MCORE_USER_RESERVED_SIZE

#ifndef GLOBAL_MEM_CORE_SHARE_ADDR
#define GLOBAL_MEM_CORE_SHARE_ADDR ((GLOBAL_MEM_MCORE_USER_RESERVED_ADDR) + (GLOBAL_MEM_MCORE_USER_RESERVED_SIZE)) 
#endif // GLOBAL_MEM_CORE_SHARE_ADDR

#ifndef GLOBAL_MEM_CORE_SHARE_SIZE
#define GLOBAL_MEM_CORE_SHARE_SIZE 0x100000 
#endif // GLOBAL_MEM_CORE_SHARE_SIZE

#ifndef GLOBAL_MEM_ACORE_BASE_ADDR
#define GLOBAL_MEM_ACORE_BASE_ADDR ((GLOBAL_MEM_CORE_SHARE_ADDR) + (GLOBAL_MEM_CORE_SHARE_SIZE)) 
#endif // GLOBAL_MEM_ACORE_BASE_ADDR

#ifndef GLOBAL_MEM_ACORE_BASE_SIZE
#define GLOBAL_MEM_ACORE_BASE_SIZE 0x2C00000 
#endif // GLOBAL_MEM_ACORE_BASE_SIZE

#ifndef GLOBAL_MEM_GU_RESERVED_ADDR
#define GLOBAL_MEM_GU_RESERVED_ADDR ((GLOBAL_MEM_ACORE_BASE_ADDR) + (GLOBAL_MEM_ACORE_BASE_SIZE)) 
#endif // GLOBAL_MEM_GU_RESERVED_ADDR

#ifndef GLOBAL_MEM_GU_RESERVED_ADDR_VIRT
#define GLOBAL_MEM_GU_RESERVED_ADDR_VIRT 0xF3F00000 
#endif // GLOBAL_MEM_GU_RESERVED_ADDR_VIRT

#ifndef GLOBAL_MEM_GU_RESERVED_SIZE
#define GLOBAL_MEM_GU_RESERVED_SIZE 0xF80000 
#endif // GLOBAL_MEM_GU_RESERVED_SIZE

#ifndef GLOBAL_LNV_BASE_ADDR
#define GLOBAL_LNV_BASE_ADDR ((GLOBAL_MEM_GU_RESERVED_ADDR) + (GLOBAL_MEM_GU_RESERVED_SIZE)) 
#endif // GLOBAL_LNV_BASE_ADDR

#ifndef GLOBAL_LNV_BASE_SIZE
#define GLOBAL_LNV_BASE_SIZE 0x80000 
#endif // GLOBAL_LNV_BASE_SIZE

#ifndef GLOBAL_MEM_LCS_ADDR
#define GLOBAL_MEM_LCS_ADDR ((GLOBAL_LNV_BASE_ADDR) + (GLOBAL_LNV_BASE_SIZE)) 
#endif // GLOBAL_MEM_LCS_ADDR

#ifndef GLOBAL_MEM_LCS_SIZE
#define GLOBAL_MEM_LCS_SIZE 0x0 
#endif // GLOBAL_MEM_LCS_SIZE

#ifndef GLOBAL_MEM_HIFI_ADDR
#define GLOBAL_MEM_HIFI_ADDR ((GLOBAL_MEM_LCS_ADDR) + (GLOBAL_MEM_LCS_SIZE)) 
#endif // GLOBAL_MEM_HIFI_ADDR

#ifndef GLOBAL_MEM_HIFI_SIZE
#define GLOBAL_MEM_HIFI_SIZE 0x0 
#endif // GLOBAL_MEM_HIFI_SIZE

#ifndef GLOBAL_MEM_SOCP_ADDR
#define GLOBAL_MEM_SOCP_ADDR ((GLOBAL_MEM_HIFI_ADDR) + (GLOBAL_MEM_HIFI_SIZE)) 
#endif // GLOBAL_MEM_SOCP_ADDR

#ifndef GLOBAL_MEM_SOCP_SIZE
#define GLOBAL_MEM_SOCP_SIZE 0x200000 
#endif // GLOBAL_MEM_SOCP_SIZE

#ifndef GLOBAL_MEM_TDS_LH2_ADDR        	
#define GLOBAL_MEM_TDS_LH2_ADDR        	 ((GLOBAL_MEM_SOCP_ADDR) + (GLOBAL_MEM_SOCP_SIZE)) 
#endif // GLOBAL_MEM_TDS_LH2_ADDR        	

#ifndef GLOBAL_MEM_TDS_LH2_SIZE        	
#define GLOBAL_MEM_TDS_LH2_SIZE        	 0x300000 
#endif // GLOBAL_MEM_TDS_LH2_SIZE        	

#ifndef GLOBAL_MEM_MCORE_ACP_ADDR
#define GLOBAL_MEM_MCORE_ACP_ADDR ((GLOBAL_MEM_TDS_LH2_ADDR) + (GLOBAL_MEM_TDS_LH2_SIZE)) 
#endif // GLOBAL_MEM_MCORE_ACP_ADDR

#ifndef GLOBAL_MEM_MCORE_ACP_SIZE
#define GLOBAL_MEM_MCORE_ACP_SIZE 0x000000 
#endif // GLOBAL_MEM_MCORE_ACP_SIZE

#ifndef CORESHARE_MEM_ADDR
#define CORESHARE_MEM_ADDR GLOBAL_MEM_CORE_SHARE_ADDR 
#endif // CORESHARE_MEM_ADDR

#ifndef CORESHARE_MEM_SIZE
#define CORESHARE_MEM_SIZE GLOBAL_MEM_CORE_SHARE_SIZE 
#endif // CORESHARE_MEM_SIZE

#ifndef CORESHARE_MEM_TOP_ADDR
#define CORESHARE_MEM_TOP_ADDR ((CORESHARE_MEM_ADDR) + (CORESHARE_MEM_SIZE)) 
#endif // CORESHARE_MEM_TOP_ADDR

#ifndef CORESHARE_MEM_SYNC_SIZE
#define CORESHARE_MEM_SYNC_SIZE 0x60 
#endif // CORESHARE_MEM_SYNC_SIZE

#ifndef CORESHARE_MEM_SYNC_ADDR
#define CORESHARE_MEM_SYNC_ADDR ((CORESHARE_MEM_TOP_ADDR) - (CORESHARE_MEM_SYNC_SIZE)) 
#endif // CORESHARE_MEM_SYNC_ADDR

#ifndef CORESHARE_MEM_SPINLOCK_SIZE
#define CORESHARE_MEM_SPINLOCK_SIZE 0x20 
#endif // CORESHARE_MEM_SPINLOCK_SIZE

#ifndef CORESHARE_MEM_SPINLOCK_ADDR
#define CORESHARE_MEM_SPINLOCK_ADDR ((CORESHARE_MEM_SYNC_ADDR) - (CORESHARE_MEM_SPINLOCK_SIZE)) 
#endif // CORESHARE_MEM_SPINLOCK_ADDR

#ifndef CORESHARE_MEM_ICC_SIZE
#define CORESHARE_MEM_ICC_SIZE 0x80 
#endif // CORESHARE_MEM_ICC_SIZE

#ifndef CORESHARE_MEM_ICC_ADDR
#define CORESHARE_MEM_ICC_ADDR ((CORESHARE_MEM_SPINLOCK_ADDR) - (CORESHARE_MEM_ICC_SIZE)) 
#endif // CORESHARE_MEM_ICC_ADDR

#ifndef CORESHARE_MEM_TENCILICA_MULT_BAND_SIZE
#define CORESHARE_MEM_TENCILICA_MULT_BAND_SIZE 0x8000 
#endif // CORESHARE_MEM_TENCILICA_MULT_BAND_SIZE

#ifndef CORESHARE_MEM_TENCILICA_MULT_BAND_ADDR
#define CORESHARE_MEM_TENCILICA_MULT_BAND_ADDR ((CORESHARE_MEM_ICC_ADDR) - (CORESHARE_MEM_TENCILICA_MULT_BAND_SIZE)) 
#endif // CORESHARE_MEM_TENCILICA_MULT_BAND_ADDR

#ifndef CORESHARE_MEM_IPC_SIZE
#define CORESHARE_MEM_IPC_SIZE 0x20 
#endif // CORESHARE_MEM_IPC_SIZE

#ifndef CORESHARE_MEM_IPC_ADDR
#define CORESHARE_MEM_IPC_ADDR ((CORESHARE_MEM_TENCILICA_MULT_BAND_ADDR) - (CORESHARE_MEM_IPC_SIZE)) 
#endif // CORESHARE_MEM_IPC_ADDR

#ifndef CORESHARE_MEM_HW_INFO_SIZE
#define CORESHARE_MEM_HW_INFO_SIZE 0x40 
#endif // CORESHARE_MEM_HW_INFO_SIZE

#ifndef CORESHARE_MEM_HW_INFO_ADDR
#define CORESHARE_MEM_HW_INFO_ADDR ((CORESHARE_MEM_IPC_ADDR) - (CORESHARE_MEM_HW_INFO_SIZE)) 
#endif // CORESHARE_MEM_HW_INFO_ADDR

#ifndef CORESHARE_MEM_WAN_SIZE
#define CORESHARE_MEM_WAN_SIZE 0x8000 
#endif // CORESHARE_MEM_WAN_SIZE

#ifndef CORESHARE_MEM_WAN_ADDR
#define CORESHARE_MEM_WAN_ADDR ((CORESHARE_MEM_HW_INFO_ADDR) - (CORESHARE_MEM_WAN_SIZE)) 
#endif // CORESHARE_MEM_WAN_ADDR

#ifndef CORESHARE_MEM_SHORT_ONOFF_SIZE
#define CORESHARE_MEM_SHORT_ONOFF_SIZE 0x20 
#endif // CORESHARE_MEM_SHORT_ONOFF_SIZE

#ifndef CORESHARE_MEM_SHORT_ONOFF_ADDR
#define CORESHARE_MEM_SHORT_ONOFF_ADDR ((CORESHARE_MEM_WAN_ADDR) - (CORESHARE_MEM_SHORT_ONOFF_SIZE)) 
#endif // CORESHARE_MEM_SHORT_ONOFF_ADDR

#ifndef CORESHARE_MEM_MEMMGR_SIZE
#define CORESHARE_MEM_MEMMGR_SIZE ((CORESHARE_MEM_SHORT_ONOFF_ADDR) - (CORESHARE_MEM_MEMMGR_ADDR)) 
#endif // CORESHARE_MEM_MEMMGR_SIZE

#ifndef CORESHARE_MEM_MEMMGR_ADDR
#define CORESHARE_MEM_MEMMGR_ADDR CORESHARE_MEM_ADDR 
#endif // CORESHARE_MEM_MEMMGR_ADDR

#ifndef GLOBAL_MEM_GUNV_RESV_VIRT
#define GLOBAL_MEM_GUNV_RESV_VIRT (0xFF3B0000) 
#endif // GLOBAL_MEM_GUNV_RESV_VIRT

#ifndef GLOBAL_MEM_GUNV_RESV_PHYS
#define GLOBAL_MEM_GUNV_RESV_PHYS (GLOBAL_MEM_GU_RESERVED_ADDR + GLOBAL_MEM_GU_RESERVED_SIZE - 0x50000) 
#endif // GLOBAL_MEM_GUNV_RESV_PHYS

#ifndef GLOBAL_MEM_GUNV_RESV_SIZE
#define GLOBAL_MEM_GUNV_RESV_SIZE (0x30000) 
#endif // GLOBAL_MEM_GUNV_RESV_SIZE

#ifndef GLOBAL_AXI_TEMP_PROTECT_ADDR
#define GLOBAL_AXI_TEMP_PROTECT_ADDR 0x2FFFE218 
#endif // GLOBAL_AXI_TEMP_PROTECT_ADDR

#ifndef GLOBAL_AXI_TEMP_PROTECT_SIZE
#define GLOBAL_AXI_TEMP_PROTECT_SIZE (128) 
#endif // GLOBAL_AXI_TEMP_PROTECT_SIZE

#ifndef GLOBAL_AXI_DICC_ADDR
#define GLOBAL_AXI_DICC_ADDR 0x2FFFFEC0 
#endif // GLOBAL_AXI_DICC_ADDR

#ifndef GLOBAL_AXI_DICC_SIZE
#define GLOBAL_AXI_DICC_SIZE (32) 
#endif // GLOBAL_AXI_DICC_SIZE

#ifndef HUAWEI_FEATURE_TEMP_SMOOTH
#define HUAWEI_FEATURE_TEMP_SMOOTH 
#endif // HUAWEI_FEATURE_TEMP_SMOOTH

#ifndef HUAWEI_FEATURE_DL_FLOW_CTRL
#define HUAWEI_FEATURE_DL_FLOW_CTRL 
#endif // HUAWEI_FEATURE_DL_FLOW_CTRL

#ifndef HUAWEI_FEATURE_UL_FLOW_CTRL
#endif // HUAWEI_FEATURE_UL_FLOW_CTRL

#ifndef FEATURE_VOLT_PERCENT
#define FEATURE_VOLT_PERCENT 
#endif // FEATURE_VOLT_PERCENT

#ifdef OBC_IMAGE_MODEM
#define PRODUCT_CFG_CORE_TYPE_MODEM 
#define PRODUCT_CFG_OS_TYPE_VXWORKS 
#define PRODUCT_CFG_IMAGE_TYPE_VXWORKS 
#define PRODUCT_CFG_IMAGE_NAME "VXWORKS" 
#define PRODUCT_CFG_DEV_USE_DRX 
#define PRODUCT_CFG_APPIMG_INCLUDE 
#define PRODUCT_CFG_DEV_USE_ABBIN 
#endif // OBC_IMAGE_MODEM

#ifdef OBC_IMAGE_APP
#define PRODUCT_CFG_OS_TYPE_LINUX 
#define PRODUCT_CFG_IMAGE_TYPE_linux 
#define PRODUCT_CFG_IMAGE_NAME "linux" 
#define PRODUCT_CFG_DEV_USE_SDIO 
#define PRODUCT_CFG_DEV_USE_JUSB 
#define PRODUCT_CFG_DEV_USE_ACM 
#define PRODUCT_CFG_DEV_USE_NCM 
#define PRODUCT_CFG_DEV_USE_MASS 
#define PRODUCT_CFG_APPIMG_INCLUDE 
#endif // OBC_IMAGE_APP

#ifdef OBC_IMAGE_BOOTROM
#define PRODUCT_CFG_CORE_TYPE_MODEM 
#define PRODUCT_CFG_OS_TYPE_VXWORKS 
#define PRODUCT_CFG_IMAGE_NAME "BOOTROM" 
#define PRODUCT_CFG_DEV_USE_JUSB 
#define PRODUCT_CFG_DEV_USE_ACM 
#define PRODUCT_CFG_APPIMG_INCLUDE 
#endif // OBC_IMAGE_BOOTROM

#ifdef OBC_IMAGE_BOOTLOADER
#define PRODUCT_CFG_IMAGE_NAME "BOOTLOADER" 
#define PRODUCT_CFG_APPIMG_INCLUDE 
#define PRODUCT_CFG_DEV_USE_DDR1 
#endif // OBC_IMAGE_BOOTLOADER

#endif //__PRODUCT_CONFIG_H__ 
