
EXTRA_CFLAGS   			+= -Idrivers/multicore/icc/
EXTRA_CFLAGS                    += -Idrivers/jusb/port/include/device/
EXTRA_CFLAGS   			+= -Idrivers/jusb/port/include/
EXTRA_CFLAGS   			+= -Idrivers/jusb/port/linux/
#EXTRA_CFLAGS   			+= -Idrivers/usb/port/defines/
EXTRA_CFLAGS   			+= -Idrivers/jusb/adapt/acm/
EXTRA_CFLAGS   			+= -Idrivers/jusb/adapt/ncm/
EXTRA_CFLAGS   			+= -Idrivers/jusb/jslave/include

EXTRA_CFLAGS                    += -Idrivers/jusb/include/
EXTRA_CFLAGS                    += -Idrivers/jusb/config/
EXTRA_CFLAGS                    += -Idrivers/jusb/

obj-y				:= bsp_udi.o bsp_udi_adp.o

