
EXTRA_CFLAGS   			+= -Idrivers/multicore/udi/
EXTRA_CFLAGS   			+= -Idrivers/multicore/ipcm/
EXTRA_CFLAGS   			+= -Idrivers/mntn/include/
EXTRA_CFLAGS   			+= -Idrivers/mntn

obj-y		:= bsp_icc.o bsp_icc_om.o
